### ISSUE TITLE
Android - ShareLinkContent.Builder; about half of the functions return Java.Lang.Object

### ISSUE THREAD

**Issue by corjohnson** [xamarin/FacebookComponents#69]
I find this quite odd, in order to make use of the builder in order to share a post with facebook, you're having to cast the result of a builder operation.

```
var builder = new ShareLinkContent.Builder()
    .SetQuote(postCaption)
    .SetContentUrl(Android.Net.Uri.Parse(postImageUrl)) as ShareLinkContent.Builder;

var shareContent = builder.Build();
```

This is nuts! Is this caused by a binding issue in the Android sdk?

**Comment by Redth** [comment]
Apologies, but this issue is a bit harder to resolve properly than it seems.

`ShareLinkContent.Builder` subclasses `ShareContent.Builder<TContent, TBuilder>` which has the method `SetContentUrl(..)` method returning `TBuilder`.  Unfortunately our binding generation code doesn't automatically handle these cases very well, and instead it returns `Java.Lang.Object` in the managed binding.  Of course the underlying type is actually `ShareLinkContent.Builder` in this case and that's why casting works and is necessary.  

We don't have any immediate plans to address this in the binding as it requires a lot of manual effort.  You are using one of the recommended approaches (the other being calling `.JavaCast<ShareLinkContent.Builder>()`) and I suggest you keep using it for now.

Hopefully the automated binding generator will improve to handle these generics cases in the not too distant future.  Sorry for the trouble!

**Comment by corjohnson** [comment]
@Redth No worries, appreciate the response & explanation.
