### ISSUE TITLE
[URGENT] Update Facebook SDK to version 4.37.0

### ISSUE THREAD

**Issue by peppe130** [xamarin/FacebookComponents#92]
Hi,

I'm unable to login into my App using Facebook API because this library's SDK is out of date. In the output console the following message appears: "Your Facebook SDK is out of date. We recommend upgrading to the latest Version 4.37.0, to ensure your app's performance is not affected and to take advantage of our newest features!".

Please, could you update this library to the latest SDK? Thank you in advance.

**Comment by marcobaldo** [comment]
Not encountering the same issue but Facebook contacted me and said we're in violation of Platform Policy 8.2, otherwise the app will be subject to enforcement:

> Please make sure your app is using the most recent version of our SDK for Login. You can find more information on our SDK for Login and other Login-related products here: https://developers.facebook.com/docs/facebook-login.

I was about to build manually from source but realized it's only on 4.36.0.

**Comment by peppe130** [comment]
> Not encountering the same issue but Facebook contacted me and said we're in violation of Platform Policy 8.2, otherwise the app will be subject to enforcement:
> 
> > Please make sure your app is using the most recent version of our SDK for Login. You can find more information on our SDK for Login and other Login-related products here: https://developers.facebook.com/docs/facebook-login.
> 
> I was about to build manually from source but realized it's only on 4.36.0.

Which version are you using currently?

**Comment by marcobaldo** [comment]
@peppe130 currently using the latest version from NuGet, 4.34.0, which is using the recently deprecated API v2.7

https://www.nuget.org/packages/Xamarin.Facebook.Android/
https://developers.facebook.com/docs/graph-api/changelog/version2.7

**Comment by Redth** [comment]
I don't believe 4.36 vs 4.37 is the issue here.  According to facebook's docs, API 3.0 will only start to be required as of Jan 8, 2019.

The error suggests updating to the latest version of the SDK which is 4.37 and we will work to release ASAP, however I don't believe in either of these cases that it alone will fix your issues.

Any more information you can get out of the policy violation details from your app account would be helpful here.

**Comment by marcobaldo** [comment]
Thanks @Redth. I personally didn't encounter the login issue @peppe130 posted, our logins still work just fine. However, our app is in danger of being marked for removal due to the SDK version violation. 

Not sure how common these checks happen but the email I received from Facebook doesn't appear to be automated and I was able to request for an extension from the case manager by sending them links to similar SDK update requests in this repo.

**Comment by Redth** [comment]
@marcobaldo not sure what version you're using, but according to Facebook's docs, 4.35 is using Graph API 3.1 which means our current stable version should be using 3.1 as well.  One thing I've noticed in my own apps is having to go into the Facebook developer console and change the version my particular application was using _there_.  Perhaps that's something to investigate?

**Comment by newky2k** [comment]
@peppe130 @marcobaldo We have pushed out an update for Android to 3.7 and iOS will be updated next week.

Regards

**Comment by peppe130** [comment]
> @peppe130 @marcobaldo We have pushed out an update for Android to 3.7 and iOS will be updated next week.
> 
> Regards

Thank you so much man.

**Comment by zonkzen** [comment]
Again, this issue should not be closed!!
